name: CI - Test Features

on:
  push:
    branches:
      - develop
    paths:
      - "features/**"
  pull_request:
    paths:
      - "features/**"
  workflow_dispatch:

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.set-matrix.outputs.features }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect features
        id: set-matrix
        run: |
          features=$(ls -d features/src/*/ | xargs -n1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "features=$features" >> $GITHUB_OUTPUT

  test:
    needs: detect
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: ${{ fromJson(needs.detect.outputs.features) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test feature
        working-directory: features
        run: |
          devcontainer features test \
            -f ${{ matrix.feature }} \
            --skip-autogenerated
